### ISSUE TITLE
JavaFX / OpenFX dependency

### ISSUE THREAD

**Issue by kpocius** [enthusiast94/kafka-visualizer#1]
While I'm sure most users can figure that out themselves, I think it would be great to note in the documentation that JavaFX or OpenFX is a prerequisite for the build to work.

**Comment by enthusiast94** [comment]
Yep, I'm using Observable collections from JavaFX, but since it's included in JDK 8 I didn't think it was necessary to explicitly list it as a requirement.

**Comment by kpocius** [comment]
I guess it depends on the platform - I have OpenJDK8 installed on Fedora, including -devel, but I had to install OpenFX separately for it to compile.

**Comment by pawelantczak** [comment]
Hi.
Headless JDK doesn't contain FX.
Regards.

**Comment by enthusiast94** [comment]
You guys are right, I should include JavaFX as a requirement in the README. Thanks for your comments.
