### ISSUE TITLE
Module build failed: BrowserslistError: Unknown browser query `>= 1%`

### ISSUE THREAD

**Issue by xdjiangyang** [enthusiast94/kafka-visualizer#2]
I built the project at Ubuntu 17.10 and met some problems as below. Would you please help me to figure it out. 

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] kafka-visualizer
[INFO] kafka-visualizer-web
[INFO] kafka-visualizer-rest
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building kafka-visualizer 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building kafka-visualizer-web 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.3.2:exec (npm-install) @ kafka-visualizer-web ---
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-visualizer-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/src/main/resources
[INFO] skip non existing resourceDirectory /home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kafka-visualizer-web ---
[INFO] No sources to compile
[INFO] 
[INFO] --- exec-maven-plugin:1.3.2:exec (npm-build-prod) @ kafka-visualizer-web ---

> client@0.0.0 build /home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web
> ng build

 94% asset oDate: 2018-01-11T07:45:41.102Z                                              
Hash: eae90c050868b7650d8f
Time: 13729ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 59.8 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 218 kB {inline} [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 225 kB {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 53.4 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.29 MB [initial] [rendered]                                                                                                    
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader?{"ident":"postcss"}!./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser query `>= 1%`
    at error (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/browserslist/index.js:37:11)
    at /home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/browserslist/index.js:222:9
    at Array.forEach (native)
    at browserslist (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/postcss/lib/lazy-result.js:274:20)
    at LazyResult.asyncTick (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/postcss/lib/lazy-result.js:189:32)
    at LazyResult.asyncTick (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/postcss/lib/lazy-result.js:201:22)
    at processing.Promise.then._this2.processed (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/postcss/lib/lazy-result.js:228:20)
    at LazyResult.async (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/postcss/lib/lazy-result.js:225:27)
    at LazyResult.then (/home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/postcss/lib/lazy-result.js:131:21)
    at /home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/node_modules/postcss-loader/index.js:129:55
 @ ./node_modules/bootstrap/dist/css/bootstrap.min.css 4:14-127
 @ multi ./src/styles.css ./node_modules/bootstrap/dist/css/bootstrap.min.css ./node_modules/font-awesome/css/font-awesome.min.css

npm ERR! Linux 4.13.0-16-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build" "--prod"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! client@0.0.0 build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client@0.0.0 build script 'ng build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jy/kafka-visualizer/kafkavisualizer/kafka-visualizer-web/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] kafka-visualizer ................................... SUCCESS [  0.005 s]
[INFO] kafka-visualizer-web ............................... FAILURE [ 31.540 s]
[INFO] kafka-visualizer-rest .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.301 s
[INFO] Finished at: 2018-01-11T15:45:41+08:00
[INFO] Final Memory: 14M/47M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (npm-build-prod) on project kafka-visualizer-web: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kafka-visualizer-web

**Comment by enthusiast94** [comment]
Hi, I've never experienced this issue myself since my development OS is Windows. However, a quick google search lead me to this page which might be useful to you: https://github.com/angular/angular-cli/issues/3938.

**Comment by enthusiast94** [comment]
Did you manage to fix this? @xdjiangyang

**Comment by xdjiangyang** [comment]
@enthusiast94  Sorry to answer you so late. I tried openjdk 1.8 and openjdk 1.9 on Ubuntu 17.04 and Ubuntu 17.10, and it still did not work...  Thank you anyway
