### ISSUE TITLE
Package to Docker then publish to Docker Hub?

### ISSUE THREAD

**Issue by jiminhsieh** [enthusiast94/kafka-visualizer#3]
I think it's a good idea since not all of the people use Java 9 locally. And if anyone needs it, he or she can just pull the image.

**Comment by enthusiast94** [comment]
That's a great idea! Will try to get this done by end of week. Thanks for the suggestion.

**Comment by labedzkim** [comment]
Hi! Did you already put it onto hub? What's the repo/image name? Best regards, Maciej.

**Comment by enthusiast94** [comment]
@labedzkim Nah, have been really busy in the last few weeks. I do definitely plan to do this though. In the meantime, if you want to continue using java 8, you can revert the most recent commit in your fork.

**Comment by dupf** [comment]
what is the default port of the work

**Comment by dupf** [comment]
what is the default port  of the project

**Comment by jiminhsieh** [comment]
@labedzkim If you don't mind, I can help this one with Travis CI.

**Comment by labedzkim** [comment]
Sure, go on.

**Comment by code-sauce** [comment]
any updates on this?

**Comment by jiminhsieh** [comment]
I am quite busy recently. If anyone wants to take over, please go ahead.

**Comment by karan1525** [comment]
Hey, 
I went ahead and created a dockerfile for this Kafka-visualizer. 
You can access it here -> https://github.com/karan1525/Kafka-Visualizer/blob/master/Dockerfile

It is also pushed to the docker hub under -> kbhargava/kafka-visuals

Hope this helps!

**Comment by enthusiast94** [comment]
@karan1525 Thanks for that! Could you also please submit a PR to include the docker file to this project?

**Comment by karan1525** [comment]
@enthusiast94 Created a PR :)

**Comment by enthusiast94** [comment]
Merged.
