### ISSUE TITLE
Backend does not listen?

### ISSUE THREAD

**Issue by labedzkim** [enthusiast94/kafka-visualizer#4]
The service does not listen although it reports that the embedded Tomcat is initialized.
`Tomcat initialized with port(s): 8080 (http)`
No errors are reported.

I've tried the latest commit with Java9 and then checked out commit 492a3670ec0c8d0ba55981b52c2562350e6758e6 and tried Java8. Still the same problem. 

Now, with Java8, I'm using the following command:
`java -jar kafka-visualizer-rest-1.0-SNAPSHOT.jar --zookeeper=localhost:2181 --env=PROD --kafka=localhost:9094`

**Comment by enthusiast94** [comment]
What does the server log look like? Should print the following when it's ready to serve requests:

2018-02-27 17:57:45.964  INFO 15772 --- [main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2018-02-27 17:57:45.970  INFO 15772 --- [main] com.enthusiast94.kafkavisualizer.App     : Started App in 12.262 seconds (JVM running for 13.85)

**Comment by labedzkim** [comment]
I can't find the 'Started App in...' in my stdout. It looks like the application hangs on something. Here is my log: https://gist.github.com/labedzkim/bc195fab4cb47cf0729217757d2e5bc0.

**Comment by enthusiast94** [comment]
Hmm that's odd. After adding all the topics, it should move onto brokers and then start consuming messages from all these topics. In your case it seems to get stuck during the topic finding stage. Since I won't be able to reproduce this issue on my machine, you'll have to debug this by running the app in development mode (instructions included in the README.md). All the topic finding logic is contained within com.enthusiast94.kafkavisualizer.service.KafkaTopicsTracker.

**Comment by labedzkim** [comment]
In debug mode I've found some errors related to wrong configuration of kafka listeners. Need to check it.

**Comment by labedzkim** [comment]
I migrated from wurstmeister/kafka docker distribution to Confluent and now it's ok.

**Comment by enthusiast94** [comment]
Oh so you were running it in docker? Do you mind contributing your docker integration work to this repo? It would be super useful to others as well. Thanks!

**Comment by labedzkim** [comment]
Hey! I'm not excluding this option. Now I'm running this as an outside-docker service but I'm a docker container seems unavoidable. When I have I'll make a pull request. Cheers!
