### ISSUE TITLE
when run java -..   I can not visit the default 8080 port

### ISSUE THREAD

**Issue by dupf** [enthusiast94/kafka-visualizer#5]

**Comment by enthusiast94** [comment]
Please paste the server logs here so that I can see what's we ring with your setup.

**Comment by dupf** [comment]
Hi
My start command is such as this















There is not error .but I canot visit the localhost:8080 website , Is the jar file has the web .




> 在 2018年3月6日，下午3:42，Manas Bajaj <notifications@github.com> 写道：
> 
> Please paste the server logs here so that I can see what's we ring with your setup.
> 
>
